FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY apps ./apps

RUN npm install
RUN npm run build --workspace=apps/tuning-agent-typescript

FROM node:20-alpine AS production

WORKDIR /app

COPY package*.json ./
COPY apps ./apps

RUN npm install --omit=dev

COPY --from=builder /app/apps/tuning-agent-typescript/dist ./apps/tuning-agent-typescript/dist

ENV NODE_ENV=production

CMD ["node", "/app/apps/tuning-agent-typescript/dist/index.js"]
